export const EMAIL_CHANGED = "EMAIL_CHANGED";
export const PASSWORD_CHANGED = "PASSWORD_CHANGED";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";
export const ON_LOADING = "ON_LOADING";
export const NAME_CHANGED = "NAME_CHANGED"
export const TITLE_CHANGED = "TITLE_CHANGED"
export const GET_ERRORS = "GET_ERRORS"